// Downloads JetBrains Mono (400 + 600, latin subset) from Google Fonts and
// writes src/font.js with base64-embedded @font-face data. Run at build time:
//   node scripts/embed-font.js
// The generated file is committed so deploys work without network access.
// Font: JetBrains Mono, SIL Open Font License 1.1.
import { writeFileSync } from "node:fs";

const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36";

async function fetchWoff2(weight) {
  const url =
    `https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@${weight}&display=swap`;
  const css = await (await fetch(url, { headers: { "User-Agent": UA } })).text();
  // pick the latin subset block (last one in the css2 response)
  const blocks = [...css.matchAll(/\/\* (\w+) \*\/\s*@font-face\s*{[^}]*}/g)];
  const latin = blocks.filter((b) => b[1] === "latin").pop() ?? blocks.pop();
  const m = latin[0].match(/url\((https:[^)]+)\)/);
  if (!m) throw new Error(`no woff2 url for weight ${weight}`);
  const buf = Buffer.from(await (await fetch(m[1])).arrayBuffer());
  return buf.toString("base64");
}

const b64 = {};
for (const w of ["400", "600"]) {
  b64[w] = await fetchWoff2(w);
  console.log(`weight ${w}: ${b64[w].length} base64 chars`);
}

writeFileSync(
  new URL("../src/font.js", import.meta.url),
  `// Generated by scripts/embed-font.js. Do not edit by hand.\n` +
    `// JetBrains Mono, SIL Open Font License 1.1.\n` +
    `export const FONT_B64 = ${JSON.stringify(b64, null, 2)};\n`
);
console.log("wrote src/font.js");
